apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: harbor1
data:
  registry-config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      maintenance:
        uploadpurging:
          enabled: false
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      token:
        realm: $HARBOR_URL/service/token
        service: harbor-registry
        issuer: harbor-token-issuer
        rootcertbundle: /etc/registry/root.crt
