apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: harbor1
spec:
  storageClassName: gp2-csi
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/registry
