apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: harbor1
spec:
  selector:
    app: registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
    - name: registry-metrics
      port: 5001
      targetPort: 5001
