# Global configuration
global:
  storageClass: gp2-csi
  serviceType: LoadBalancer

# Harbor configuration
harbor:
  core:
    replicaCount: 1
    image: goharbor/harbor-core:v2.12.2
    storage:
      size: 5Gi
    service:
      type: LoadBalancer
      port: 80
  portal:
    replicaCount: 1
    image: goharbor/harbor-portal:v2.12.2
    service:
      type: ClusterIP
      port: 80
  jobservice:
    replicaCount: 1
    image: goharbor/harbor-jobservice:v2.12.2
    storage:
      size: 5Gi

# Registry configuration
registry:
  replicaCount: 1
  image: goharbor/registry-photon:v2.12.2
  storage:
    size: 5Gi
  service:
    type: ClusterIP
    port: 5000

# Redis configuration
redis:
  replicaCount: 1
  image: redis:6.2
  storage:
    size: 2Gi

# Trivy configuration
trivy:
  replicaCount: 1
  image: aquasec/trivy:0.37.0
  storage:
    size: 5Gi

# PostgreSQL configuration
postgresql:
  replicaCount: 1
  image: postgres:15
  storage:
    size: 10Gi
  service:
    type: ClusterIP
    port: 5432

# SSL Configuration
tls:
  secretName: harbor-ssl-secret
  crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lVTEZQaGhZN1M2RGpkaFJ2Uk1YdWpVMFYrK084d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hURWJNQmtHQTFVRUF3d1NhR0Z5WW05eUxtVjRZVzF3YkdVdVkyOXRNQjRYRFRJMU1ETXlNVEEyTXpNeApORm9YRFRJMk1ETXlNVEEyTXpNeE5Gb3dIVEViTUJrR0ExVUVBd3dTYUdGeVltOXlMbVY0WVcxd2JHVXVZMjl0Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbC91dzVzOEgxRDB3eVhsOWRZMnIKbTYxZ0p5NEhqN3NjK01rWmxkbTUxRFNNbGtGZmp2WTJXL0dPVnZuMDkzUGI4QjU1dFpLNVRKSGtsWEhBUkFMeQpEZzhmUTVxQjFFQVRpOE5FZXhKRVc1L1V3VkNtWGdZbnNkNlhzTDgvRUxDbUY3VDVxcW9jTVk3OFNySXh2UXJFCmUvN1FKakNrRFd5RGVRZkdaMUM0amVnUDhtakp1eG9HdlJRZ0Z6Mk5DbEFqb05FelRhL1pDTGFnRDY5TzFwSGUKdDQvdXlkTzM2bzMrbjArVm5XTTlzWFA2akloVTh3K0c4enNXZVB2eUZQNmtZeTEwYnpDR3FVTHFZNDE1VDJIRAp5b3lqaGZkTWdVSndDL2NwcXFrTms0NVpOdW9ZUHFYOHo3OURJbEhJWkNnSHZIRndickxtQURQZVE1L200ejFnClZ3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVU0TXRhT016SHZSTDNSRElBTFBWMUUxTnVncGN3SHdZRFZSMGoKQkJnd0ZvQVU0TXRhT016SHZSTDNSRElBTFBWMUUxTnVncGN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQWxDaSt1UFZPYjVpc21OTzNMUFBjTlFWbnJOS2JncW9WaHZUbSsydlUzeWJJCkV5UEdZb3ZKcStCSHF0VFRSMlU5WXhZMXQ4U0d1enZtQWI0UHdSY1NtSzdZdDFaTmI4Z2U5czFzYTB6aHBmMmIKeDM0RmFrQk0xbmZUcDIrcVdYZ05HaUx0K3hLc1Fiak1ieE5DcjBHQ0VQWnplRmd6U1A3eVAzSjJ1dDRpbVNnRQpzRTFmdHRibGIxQlRTRkhhcXBrWnpmSVNBRjZlM3VTbTF5SkxNeVBrL1lqL09UbTVxeWpHU0JmdGVBRmpRYlZOCit4OTRZZ1h5eThSM1BpZTE4Y3ZWTEUwK2dETzJtbjcwVnNGRjI4TXJWVmlHTDZBWHY3UEtwbXVuSTBrTEpsbXoKd0xjMllpSnJWY09zWXNhZ2Y0ZzVWVlRoT0hFbjNjK1hsbHhMM2JrOEt3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo
  key: ""
