apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobservice-pv
  namespace: harbor1
spec:
  storageClassName: gp3-csi
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/jobservice
