apiVersion: v1
kind: ConfigMap
metadata:
  name: jobservice-config
  namespace: harbor1
data:
  config.yml: |
    log:
      level: info
      formatter: text
    jobservice:
      pool:
        worker_count: 10
        redis:
          namespace: harbor_job_service_namespace
          idle_timeout_second: 30
    registry:
      url: http://harbor-registry:5000
    core:
      url: http://harbor-core:8080
      token_url: http://harbor-core:8080/service/token
    token_service:
      url: http://harbor-core:8080/service/token
