apiVersion: v1
kind: Service
metadata:
  name: jobservice
  namespace: harbor1
  labels:
    app: jobservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: jobservice
