apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-core-pv
  namespace: harbor1
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/harbor-core
