- apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: harbor-core
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: harbor-core
      template:
        metadata:
          labels:
            app: harbor-core
        spec:
          containers:
            - name: harbor-core
              image: goharbor/harbor-core:v2.12.2
              ports:
                - containerPort: 80