apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-core
  namespace: harbor1
  labels:
    app: harbor-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-core
  template:
    metadata:
      labels:
        app: harbor-core
    spec:
      containers:
        - name: harbor-core
          image: goharbor/harbor-core:v2.12.2
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: harbor-config
          env:
            - name: CACHE_ENABLED
              value: "true"
            - name: CACHE_TYPE
              value: "redis"
            - name: CACHE_REDIS_HOST
              value: "redis"
            - name: CACHE_REDIS_PORT
              value: "6379"
            - name: CACHE_REDIS_NAMESPACE
              value: "harbor_cache"
