- apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: trivy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: trivy
      template:
        metadata:
          labels:
            app: trivy
        spec:
          containers:
            - name: trivy
              image: aquasec/trivy:0.37.0
              ports:
                - containerPort: 8080