apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: harbor1
spec:
  storageClassName: gp2-csi
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis
