apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
  namespace: harbor1
data:
  NGINX_CONF: |
    server {
      listen 80;
      server_name harbor.cloudmasa.com;
      location / {
        proxy_pass http://127.0.0.1:8080;
      }
    }
