apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
  namespace: harbor1
data:
  # Add any environment variables or configuration files here
  NGINX_CONF: |
    server {
      listen 80;
      server_name harbor.cloudmasa.com;
      location / {
        proxy_pass http://portal:80;
      }
    }
