apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: harbor1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 8080  # The Harbor Portal listens on port 8080
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]  # Allows binding to port 80 as non-root
          envFrom:
            - configMapRef:
                name: portal-config
